using System;
using FentrisDesktop.Board;
using var game = new FentrisDesktop.FentrisGame();
var b = new Board();
b[4, 3] = new Block(BlockKind.Bone);
var p = new Piece(Tetrominoes.I, 0, 0, 2);
Console.WriteLine(b);
Console.WriteLine(b.CollidePiece(p, 0, 0));
Console.WriteLine(b.CollidePiece(p, 0, 2));
Console.WriteLine(b.CollidePiece(p, 1, 2));
(p.X, p.Y) = (1, 3);
b.PlacePiece(p);
Console.WriteLine(b);
var p2 = new Piece(Tetrominoes.I, 1, -2, 0);
Console.WriteLine(b.GetGhostY(p2));
p2.Y = b.GetGhostY(p2);
b.PlacePiece(p2);
Console.WriteLine(b);
b.ClearRow(18);
b.ClearRow(4);
Console.WriteLine(b);
game.Run();